#!/bin/sh
set -e

if [ "$1" = configure ]; then
	if command -v glib-compile-schemas >/dev/null; then
		glib-compile-schemas /usr/share/glib-2.0/schemas >/dev/null || true
	fi
	if command -v gtk4-update-icon-cache >/dev/null; then
		gtk4-update-icon-cache -f /usr/share/icons/hicolor >/dev/null 2>&1 || true
	elif command -v gtk-update-icon-cache >/dev/null; then
		gtk-update-icon-cache -f /usr/share/icons/hicolor >/dev/null 2>&1 || true
	fi
	if command -v update-desktop-database >/dev/null; then
		update-desktop-database -q /usr/share/applications >/dev/null 2>&1 || true
	fi
fi

#DEBHELPER#

exit 0
